apiVersion: v1
kind: Pod
metadata:
  name: service1
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/connect-service-upstreams": "service2:1234"
spec:
  containers:
    # This name will be the service name in Consul.
    - name: service1
      image: node-service-1:techleads1
      imagePullPolicy: Never
      ports:
        - containerPort: 3000
          name: http