apiVersion: v1
kind: Pod
metadata:
  name: service2-v2
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/service-meta-version": "v2"
    "consul.hashicorp.com/connect-service-upstreams": "service1:1234"

spec:
  containers:
    # This name will be the service name in Consul.
    - name: service2
      image: node-service-2:v2
      imagePullPolicy: Never
      ports:
        - containerPort: 3000
          name: http